#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CodeHubX.Droid.Wear.Resource", IsApplication=true)]

namespace CodeHubX.Droid.Wear
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.AppCenter.Push.Android.Resource.Drawable.ic_stat_notify_dot = global::CodeHubX.Droid.Wear.Resource.Drawable.ic_stat_notify_dot;
			global::Microsoft.AppCenter.Push.Android.Resource.String.library_name = global::CodeHubX.Droid.Wear.Resource.String.library_name;
			global::Xamarin.Auth.Resource.Animation.slide_in_right = global::CodeHubX.Droid.Wear.Resource.Animation.slide_in_right;
			global::Xamarin.Auth.Resource.Animation.slide_out_left = global::CodeHubX.Droid.Wear.Resource.Animation.slide_out_left;
			global::Xamarin.Auth.Resource.Drawable.ic_arrow_back = global::CodeHubX.Droid.Wear.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth.Resource.Id.text = global::CodeHubX.Droid.Wear.Resource.Id.text;
			global::Xamarin.Auth.Resource.Id.webview = global::CodeHubX.Droid.Wear.Resource.Id.webview;
			global::Xamarin.Auth.Resource.Layout.activity_webview = global::CodeHubX.Droid.Wear.Resource.Layout.activity_webview;
			global::Xamarin.Auth.Resource.String.library_name = global::CodeHubX.Droid.Wear.Resource.String.library_name;
			global::Xamarin.Auth.Resource.String.title_activity_webview = global::CodeHubX.Droid.Wear.Resource.String.title_activity_webview;
			global::Xamarin.Auth.XamarinForms.Resource.Animation.slide_in_right = global::CodeHubX.Droid.Wear.Resource.Animation.slide_in_right;
			global::Xamarin.Auth.XamarinForms.Resource.Animation.slide_out_left = global::CodeHubX.Droid.Wear.Resource.Animation.slide_out_left;
			global::Xamarin.Auth.XamarinForms.Resource.Drawable.ic_arrow_back = global::CodeHubX.Droid.Wear.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth.XamarinForms.Resource.Id.text = global::CodeHubX.Droid.Wear.Resource.Id.text;
			global::Xamarin.Auth.XamarinForms.Resource.Id.webview = global::CodeHubX.Droid.Wear.Resource.Id.webview;
			global::Xamarin.Auth.XamarinForms.Resource.Layout.activity_webview = global::CodeHubX.Droid.Wear.Resource.Layout.activity_webview;
			global::Xamarin.Auth.XamarinForms.Resource.String.ApplicationName = global::CodeHubX.Droid.Wear.Resource.String.ApplicationName;
			global::Xamarin.Auth.XamarinForms.Resource.String.Hello = global::CodeHubX.Droid.Wear.Resource.String.Hello;
			global::Xamarin.Auth.XamarinForms.Resource.String.title_activity_webview = global::CodeHubX.Droid.Wear.Resource.String.title_activity_webview;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int slide_in_right = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide_out_left = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int box_inset_layout_padding = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int inner_frame_layout_padding = 2131165185;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_stat_notify_dot = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int text = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int webview = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_webview = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int app_name = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int hello_world = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int library_name = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int title_activity_webview = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
