# https://docs.microsoft.com/vsts/pipelines/languages/xamarin
jobs:
- job: WindowsJobs
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    BuildConfiguration: 'Release'
    outDir: '$(build.binariesDirectory)/$(BuildConfiguration)'
    androidMobileProject: '**Driod.Mobile.csproj'
    androidMobileSolution: '**Android.sln'
    iosUniversalProject: '**Universal.csproj'
    iosUniversalSolution: '**Apple.sln'
    sharedProject: '**/*CodeHubX.csproj'    
    sharedTestProject: '**/[Tt]est[s]/CodeHubX[.Test].csproj'
    testProjects: '**/[Tt]est[s]/*[.Test].csproj'
    testWebProject: |
      '**/*Web.csproj'
      '**/[Tt]ests/*.Web[.Test].csproj'
    uwpProject: '**UWP.csproj'
    uwpSolution: '**UWP.sln'
    webProject: '**Web.csproj'
    webSolution: '**Web.sln'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore Shared Project'
    inputs:
      command: restore
      projects: '$(sharedProject)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Shared Project'
    inputs:
      projects: '$(sharedProject)'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Test Shared Project'
    inputs:
      command: test
      projects: '$(sharedTestProjects)'
      arguments: '--configuration $(BuildConfiguration)'
      enabled: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

  - task: DotNetCoreCLI@2
    displayName: 'Restore Web Project'
    inputs:
      command: restore
      projects: '$(webProject)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Web Project'
    inputs:
      command: build
      projects: '$(webProject)'

  - task: DotNetCoreCLI@2
    displayName: 'Restore Web Project'
    inputs:
      command: restore
      projects: '$(testWebProject)'

  - task: NuGetToolInstaller@0
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'
  - task: XamarinAndroid@1
    inputs:
      projectFile: '$(androidMobileProject)'
      outputDirectory: '$(outDir)'
      configuration: '$(BuildConfiguration)'

- job: iOS
  pool:
    vmImage: 'macOS-10.13'
  variables:
    buildConfiguration: 'Release'
  steps:
  - task: NuGetToolInstaller@0
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(iosSolution)'
  - task: XamariniOS@2
    inputs:
      solutionFile: '$(iosSolution)'
      configuration: '$(BuildConfiguration)'
      buildForSimulator: true
      packageApp: false