# Universal Windows Platform
# Build a Universal Windows Platform application using Visual Studio.
# Add steps that test and distribute the app, save build artifacts, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  project: '**/*UWP*.csptoj'
  buildPlatform: 'x86|x64|ARM'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)/AppxPackages/'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreProject: '$(project)'

- task: VSBuild@1
  inputs:
    platform: '$(buildPlatform)'
    projectFile: '**/*UWP*.csproj'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
