//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeHubX.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeHubX.Strings.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closed.
        /// </summary>
        public static string activity_ActionClosed {
            get {
                return ResourceManager.GetString("activity_ActionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opened.
        /// </summary>
        public static string activity_ActionOpened {
            get {
                return ResourceManager.GetString("activity_ActionOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reopened.
        /// </summary>
        public static string activity_ActionReOpened {
            get {
                return ResourceManager.GetString("activity_ActionReOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} issue #{1} in.
        /// </summary>
        public static string activity_ActivityWithIssues {
            get {
                return ResourceManager.GetString("activity_ActivityWithIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} PR #{1}.
        /// </summary>
        public static string activity_ActivityWithPR {
            get {
                return ResourceManager.GetString("activity_ActivityWithPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commented on commit in.
        /// </summary>
        public static string activity_CommentedCommit {
            get {
                return ResourceManager.GetString("activity_CommentedCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commented on issue #{0} in.
        /// </summary>
        public static string activity_CommentedIssue {
            get {
                return ResourceManager.GetString("activity_CommentedIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commented on PR #{0}.
        /// </summary>
        public static string activity_CommentedPR {
            get {
                return ResourceManager.GetString("activity_CommentedPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created in.
        /// </summary>
        public static string activity_CreatedBranch {
            get {
                return ResourceManager.GetString("activity_CreatedBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acted on.
        /// </summary>
        public static string activity_DefaultAction {
            get {
                return ResourceManager.GetString("activity_DefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted in.
        /// </summary>
        public static string activity_DeletedBranch {
            get {
                return ResourceManager.GetString("activity_DeletedBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forked.
        /// </summary>
        public static string activity_ForkedRepository {
            get {
                return ResourceManager.GetString("activity_ForkedRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to published a release to.
        /// </summary>
        public static string activity_PublishedRelease {
            get {
                return ResourceManager.GetString("activity_PublishedRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open sourced.
        /// </summary>
        public static string activity_PublishedRepository {
            get {
                return ResourceManager.GetString("activity_PublishedRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pushed {0} commits to.
        /// </summary>
        public static string activity_PushedCommits {
            get {
                return ResourceManager.GetString("activity_PushedCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starred.
        /// </summary>
        public static string activity_StarredRepository {
            get {
                return ResourceManager.GetString("activity_StarredRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a day ago.
        /// </summary>
        public static string aDayAgo {
            get {
                return ResourceManager.GetString("aDayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        public static string aMinuteAgo {
            get {
                return ResourceManager.GetString("aMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one month ago.
        /// </summary>
        public static string aMonthAgo {
            get {
                return ResourceManager.GetString("aMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string anHourAgo {
            get {
                return ResourceManager.GetString("anHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeHubX.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one second ago.
        /// </summary>
        public static string aSecondAgo {
            get {
                return ResourceManager.GetString("aSecondAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one year ago.
        /// </summary>
        public static string aYearAgo {
            get {
                return ResourceManager.GetString("aYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        public static string daysAgo {
            get {
                return ResourceManager.GetString("daysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        public static string hoursAgo {
            get {
                return ResourceManager.GetString("hoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to Preview.
        /// </summary>
        public static string markdownComment_NoContent {
            get {
                return ResourceManager.GetString("markdownComment_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string menu_Settings_SubMenu_About {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer info and contacts.
        /// </summary>
        public static string menu_Settings_SubMenu_About_SubText {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_About_SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string menu_Settings_SubMenu_Appearance {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI customization.
        /// </summary>
        public static string menu_Settings_SubMenu_Appearance_SubText {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_Appearance_SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string menu_Settings_SubMenu_Credits {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your contributions!.
        /// </summary>
        public static string menu_Settings_SubMenu_Credits_SubText {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_Credits_SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string menu_Settings_SubMenu_Donate {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the app and the developer.
        /// </summary>
        public static string menu_Settings_SubMenu_Donate_SubText {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_Donate_SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string menu_Settings_SubMenu_General {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App preferences.
        /// </summary>
        public static string menu_Settings_SubMenu_General_SubText {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_General_SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string menu_Settings_SubMenu_Notifications {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Notification Settings.
        /// </summary>
        public static string menu_Settings_SubMenu_Notifications_SubText {
            get {
                return ResourceManager.GetString("menu_Settings_SubMenu_Notifications_SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        public static string minutesAgo {
            get {
                return ResourceManager.GetString("minutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months ago.
        /// </summary>
        public static string monthsAgo {
            get {
                return ResourceManager.GetString("monthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet.
        /// </summary>
        public static string notification_NoInternetConnection {
            get {
                return ResourceManager.GetString("notification_NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string pageTitle_CommentView {
            get {
                return ResourceManager.GetString("pageTitle_CommentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string pageTitle_DeveloperProfileView {
            get {
                return ResourceManager.GetString("pageTitle_DeveloperProfileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Feed.
        /// </summary>
        public static string pageTitle_FeedView {
            get {
                return ResourceManager.GetString("pageTitle_FeedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string pageTitle_IssueDetailView {
            get {
                return ResourceManager.GetString("pageTitle_IssueDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string pageTitle_IssuesView {
            get {
                return ResourceManager.GetString("pageTitle_IssuesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Organizations.
        /// </summary>
        public static string pageTitle_MyOrganizationsView {
            get {
                return ResourceManager.GetString("pageTitle_MyOrganizationsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Repositories.
        /// </summary>
        public static string pageTitle_MyReposView {
            get {
                return ResourceManager.GetString("pageTitle_MyReposView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string pageTitle_NotificationsView {
            get {
                return ResourceManager.GetString("pageTitle_NotificationsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string pageTitle_OrganizationView {
            get {
                return ResourceManager.GetString("pageTitle_OrganizationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request.
        /// </summary>
        public static string pageTitle_PullRequestDetailView {
            get {
                return ResourceManager.GetString("pageTitle_PullRequestDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Requests.
        /// </summary>
        public static string pageTitle_PullRequestsView {
            get {
                return ResourceManager.GetString("pageTitle_PullRequestsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string pageTitle_RepoDetailView {
            get {
                return ResourceManager.GetString("pageTitle_RepoDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string pageTitle_SearchView {
            get {
                return ResourceManager.GetString("pageTitle_SearchView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string pageTitle_SettingsView {
            get {
                return ResourceManager.GetString("pageTitle_SettingsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending.
        /// </summary>
        public static string pageTitle_TrendingView {
            get {
                return ResourceManager.GetString("pageTitle_TrendingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds ago.
        /// </summary>
        public static string secondsAgo {
            get {
                return ResourceManager.GetString("secondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years ago.
        /// </summary>
        public static string yearsAgo {
            get {
                return ResourceManager.GetString("yearsAgo", resourceCulture);
            }
        }
    }
}
